# Generated by Django 2.2.6 on 2019-10-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp18', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='r_type',
        ),
        migrations.AlterField(
            model_name='room',
            name='r_no',
            field=models.IntegerField(),
        ),
    ]
