# Generated by Django 2.2.6 on 2019-10-19 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp18', '0005_auto_20191019_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 4, 37, 7, 420811)),
        ),
    ]
