# Generated by Django 2.2.6 on 2019-10-19 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp18', '0007_auto_20191019_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 4, 42, 23, 369102)),
        ),
    ]
