# Generated by Django 2.2.6 on 2019-10-19 05:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp18', '0012_auto_20191019_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='r_no',
        ),
        migrations.AddField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(default=101),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 5, 29, 18, 660472)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hrmsapp18.Guest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hrmsapp18.Hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hrmsapp18.Room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='standard', max_length=200),
        ),
    ]
