# Generated by Django 2.2.6 on 2019-10-19 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp18', '0027_auto_20191019_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 7, 8, 59, 530574)),
        ),
    ]
