# Generated by Django 2.2.6 on 2019-10-19 11:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp18', '0034_auto_20191019_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrmsapp18.Guest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 11, 39, 3, 380296)),
        ),
    ]
