# Generated by Django 2.2.6 on 2019-10-19 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp18', '0039_auto_20191019_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 12, 41, 40, 457953)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hrmsapp18.Manager'),
            preserve_default=False,
        ),
    ]
