# Generated by Django 2.2.6 on 2019-10-21 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp18', '0041_auto_20191019_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='gender',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='gender',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 10, 38, 30, 389345)),
        ),
    ]
