# Generated by Django 2.2.6 on 2019-10-23 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp18', '0043_auto_20191021_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 23, 11, 53, 48, 84539)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
