# Generated by Django 2.2.6 on 2019-10-24 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp18', '0049_auto_20191024_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='staff',
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 3, 52, 21, 958966)),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
