# Generated by Django 2.2.6 on 2019-10-24 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp18', '0050_auto_20191024_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 3, 56, 4, 306074)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
    ]
