# Generated by Django 2.2.6 on 2019-10-24 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp18', '0051_auto_20191024_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='gender',
        ),
        migrations.AddField(
            model_name='guest',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 3, 59, 24, 714393)),
        ),
    ]
