# Generated by Django 3.0.2 on 2020-01-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hrmsapp', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(default=101)),
                ('room_type', models.CharField(default='standard', max_length=200)),
                ('rate', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('no_of_beds', models.IntegerField(default=3)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hrmsapp.Hotel')),
            ],
        ),
    ]
