# Generated by Django 3.0.2 on 2020-01-28 11:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hrmsapp', '0003_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField(default=datetime.datetime(2020, 1, 28, 11, 23, 21, 400494))),
                ('checkout_date', models.DateTimeField(default=datetime.datetime(2020, 1, 29, 11, 23, 21, 400523))),
                ('check_out', models.BooleanField(default=False)),
                ('no_of_guests', models.IntegerField(default=1)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hrmsapp.Guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hrmsapp.Hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hrmsapp.Room')),
            ],
        ),
    ]
