# Generated by Django 3.0.2 on 2020-01-28 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrmsapp', '0009_auto_20200128_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 11, 38, 20, 722627)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 11, 38, 20, 722660)),
        ),
    ]
